- name: PLAY1
  hosts: local
  connection: local
  tasks:
     - name: play with task1
       ansible.builtin.debug:
        msg: " print the play1 with task1"

     - name: play with task2
       ansible.builtin.debug:
        msg: " print the play1 with task2"  


- name: PLAY2
  hosts: local
  connection: local
  tasks:
     - name: play with task1
       ansible.builtin.debug:
        msg: " print the play2 with task1"

     - name: play with task2
       ansible.builtin.debug:
        msg: " print the play2 with task2"        