- name: play level with variables
  host: local
  connection: local
  vars:
    course: devops with aws
    name: siva
    duration: 120 hrs
  tasks:
    - name: print the course information
      vars:
       course: devops
      ansible.builtin.debug:
       msg: 'hello {{ course }}, name is: {{ name }}, duration is {{ duration }}' 
      

    - name: print the course information
      ansible.builtin.debug:
       msg: 'hello {{ course }}, name is: {{ name }}, duration is {{ duration }}'   