- name: play level with variables
  hosts: local
  connections: local
  vars:
    course: devops
    name: siva
    duration: 120 hrs
  tasks:
    - name: print the course information
      course: devops
      ansible.builtin.debug:
      msg: 'hello {{ course }}, name is: {{ name }}, duration is {{ duration }}' 
      

    - name: print the course information
      course: devops
      ansible.builtin.debug:
      msg: 'hello {{ course }}, name is: {{ name }}, duration is {{ duration }}'   