- name: play level with variables
  hosts: local
  connection: local
  vars:
  - course.yaml
  tasks:
     - name: print the course information
       course: devops
       ansible.builtin.debug:
        msg: 'hello {{ course }}, name is: {{ name }}, duration is {{ duration }}' 
      

     - name: print the course information
       course: devops
       ansible.builtin.debug:
        msg: 'hello {{ course }}, name is: {{ name }}, duration is {{ duration }}'   