- name: play level with variables
  hosts: local
  connection: local
  vars_files:
   - course.yaml
  tasks:
     - name: print the course information
       course: aws
       ansible.builtin.debug:
        msg: 'hello {{ course }}, name is: {{ name }}, duration is {{ duration }}' 
      

     - name: print the course information
       ansible.builtin.debug:
        msg: 'hello {{ course }}, name is: {{ name }}, duration is {{ duration }}'   