- name: variables from inventory
  hosts: local
  connection: local
  tasks:
   - name: print the variable info
     ansible.builtin.debug:
      msg: "course info course is: {{ course }}, name is: {{ name }}, duration is: {{ duration }}"