- name: ansible loops
  hosts: frontend
  become: yes
  tasks:
    - name: install ansbile packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: installed
      loop:
      - mysql
      - zip
      - nginx