[frontend]
54.145.47.237 course=devops trainer=siva duration=120hrs
172.31.24.13  course=devops trainer=siva duration=120hrs

[backend]
172.31.24.13

[local]
localhost

[local:vars]
course=devops
trainer=siva
duration=120hrs
greeting=hello from greeting